// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEA9FqQ2fszrcBCLUCAiPymu-Xwxts1s4',
    appId: '1:377717717647:web:22f8ffdade731d80b30efa',
    messagingSenderId: '377717717647',
    projectId: 'split-the-bill-77907',
    authDomain: 'split-the-bill-77907.firebaseapp.com',
    storageBucket: 'split-the-bill-77907.appspot.com',
    measurementId: 'G-YYS3LCVHSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADA6Wbs0X9VKjMTDkVQ4gdh0qpxS5XcGk',
    appId: '1:377717717647:android:6042ca586adde09eb30efa',
    messagingSenderId: '377717717647',
    projectId: 'split-the-bill-77907',
    storageBucket: 'split-the-bill-77907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYIfCjutZNyD2dIT9wz257mYc6RsrZYY',
    appId: '1:377717717647:ios:a1a6f26aafe704a3b30efa',
    messagingSenderId: '377717717647',
    projectId: 'split-the-bill-77907',
    storageBucket: 'split-the-bill-77907.appspot.com',
    iosBundleId: 'com.example.splitTheBill',
  );
}
